matrix:
  include:
    - os: windows
      language: shell
      before_install:
        - choco install wixtoolset --version 3.10.3.300701
        - choco install -y openjdk --version 11.0.1
        - export JAVA_HOME="/c/Program Files/OpenJDK/jdk-11"
        - export PATH="$JAVA_HOME/jdk-11.0.1/bin:$PATH"
        - choco install maven --version 3.5.0
        - curl -o jpackager.zip http://download2.gluonhq.com/jpackager/11/jdk.packager-windows.zip
        - curl -o javafxmods.zip http://download2.gluonhq.com/openjfx/11.0.1/openjfx-11.0.1_windows-x64_bin-jmods.zip
        - unzip jpackager.zip
        - unzip javafxmods.zip
        - mv jpackager.exe "${JAVA_HOME}/bin"
        - mv jdk.packager.jar "${JAVA_HOME}/bin"
      script:
        - mvn install -e
    - os: osx
      language: java
      jdk: openjdk11
      before_install:
        - curl -o jpackager.zip http://download2.gluonhq.com/jpackager/11/jdk.packager-osx.zip
        - curl -o javafxmods.zip http://download2.gluonhq.com/openjfx/11.0.1/openjfx-11.0.1_osx-x64_bin-jmods.zip
        - unzip jpackager.zip
        - unzip javafxmods.zip
    - os: linux
      language: java
      jdk: openjdk11
      before_install:
        - sudo apt-get install fakeroot
        - curl -o jpackager.zip http://download2.gluonhq.com/jpackager/11/jdk.packager-linux.zip
        - curl -o javafxmods.zip http://download2.gluonhq.com/openjfx/11.0.1/openjfx-11.0.1_linux-x64_bin-jmods.zip
        - unzip jpackager.zip
        - unzip javafxmods.zip
deploy:
  provider: releases
  api_key:
    secure: fb0fc9XePMiJjYI9TuhbmubYEAuFFRIuyz7oTbmeqZ1vqt6hLFpTmQHo5keHxPv1O/XYscydwOCAP220Fw/a7LW1sG4QLBOP4o/096r9fBSIguH0PAvpmwh0C8VlpQyn5HK8Qm8L+ALz85j7jUXsH0DJoGTLvdrvG+qcSfs/fBrVPoM5QdNSERhk6vVMgD82VUBXEraBfCrqjotInuRN87RqRLuPiBJ5aLfeKkeeUC8893X+U7HdcJ8JRzdzBDketBzb04zNvekY/oizNmYB/06r3kayuIW+SfYSLysyVU1dsPcRNEl2moTOoIuSKWDB5GladSv8VbvVzt8bvz8sCul3RtNWNZRyKy0o3ks7snOUcXoH5U0Z8231mtZ4nD25CBptvYxzYNhapeO/hVZBB3GrgBYxo1m7wiBrLotPLRiSRvZGNdPqwAszq0q14v/e6pWRvCUrlpf+5gKURN2Hwswy/jW19Oy8cutZisIilV9iF7P5xJU2mFD76TehJJoOvZWIJ0BcJ6m25l4cRzHtKOh5N8Bsiv15vYpajI3/BqQJ3ZMKFFFKgtxusCLSbSn2wkPpkC1DpfwsIFsH53/EBz/HPFYpD2qhHJhK14nmzCLhk0i2Q4caJReBsVIBioWqPrPwvVnfa3oBJzxOJ7OCBYNtAC++SM9sl1tsYwlR98Y=
  file_glob: true
  file: target/release/*
  skip_cleanup: true
  draft: true
  on:
    branch: master
    tags: true