matrix:
  include:
    - os: windows
      language: shell
      before_install:
        - choco install wixtoolset --version 3.10.3.300701
        - choco install openjdk11 --version 11.0.8.10
        - export JAVA_HOME="/c/Program Files/OpenJDK/openjdk-11.0.8_10"
        - export PATH="$JAVA_HOME/bin:$PATH"
        - choco install maven --version 3.5.0
        - curl -o jpackager.zip http://download2.gluonhq.com/jpackager/11/jdk.packager-windows.zip
        - curl -o javafxmods.zip http://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_windows-x64_bin-jmods.zip
        - unzip jpackager.zip
        - unzip javafxmods.zip
        - mv jpackager.exe "${JAVA_HOME}/bin"
        - mv jdk.packager.jar "${JAVA_HOME}/bin"
      script:
        - mvn install -e
    - os: osx
      language: java
      jdk: openjdk11
      before_install:
        - curl -o jpackager.zip http://download2.gluonhq.com/jpackager/11/jdk.packager-osx.zip
        - curl -o javafxmods.zip http://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_osx-x64_bin-jmods.zip
        - unzip jpackager.zip
        - unzip javafxmods.zip
    - os: linux
      language: java
      jdk: openjdk11
      before_install:
        - sudo apt-get install fakeroot
        - curl -o jpackager.zip http://download2.gluonhq.com/jpackager/11/jdk.packager-linux.zip
        - curl -o javafxmods.zip http://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_linux-x64_bin-jmods.zip
        - unzip jpackager.zip
        - unzip javafxmods.zip
deploy:
  provider: releases
  api_key:
    secure: oD982aFR1/4BfxZejUmu3Avm34q5pljsC4+REidrye9AQAIMRtgo6upJEfSZ5Uo13hJQq8x2rS3j/H3pN7cCMI3exudoSn0r3AZ0xJPHMHQi9cx4GnjGsa8E6j+LNe5MRR6D/eG7WuGP8MlearwgVov0nyCIhaJsTycpuK4eywmH9npAZFUCZroggUzB/sGf86cN5Ur/CzgiJR3ZtL0rX8Iv2+2pJ+SSScRh4EKSf9bCcM7sHZmK4dig2ESUa8VELsQwqto2+fgYgXZuEs++kNaHvQUdOVIzi6/Bc/oSK2hnsRhRzY7mzla8wz1tcMjLqwSTyMs3/OaZGUfA1T0yAKdPp/LzAgtvMcE4XgbsnvFfXWINK8VGyVEb2SQlCO8pUO117/MufqG/Kh1AcyqSRpGopy7foi8cV2xuEjDr36n60Z/hAA1mpcgV/vGmK3jZ4JjHh2ZQadpy7UsNeBtl8c9fTKlrAaCwo13fMttQvDzsJqlvutI0U6LOvjG3h+zs7m1JIraNMZza1C/1JUe8Zy43qdXXMFdS+5i3qD9qQPM5yU34R86CLscBx4LBPKj4jad3xpGBgjjaG5BsZmeFGqRzKjRpYFWWn6mgjaxpR0k5CycDifq39ugOaLcLmGPl24NDqD0nwOFPsUHsld9dmCoLA+HdUfW1jw1AhltnWXg=
  file_glob: true
  file: target/release/*
  skip_cleanup: true
  draft: true
  on:
    branch: master
    tags: true