on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        include:
        - os: windows-latest
          display-name: 'windows'
          installerName: 'btviewer.msi'
          jpackagerDownloadUrl: 'http://download2.gluonhq.com/jpackager/11/jdk.packager-windows.zip'
        - os: ubuntu-latest
          display-name: 'linux'
          installerName: 'btviewer.deb'
          jpackagerDownloadUrl: 'http://download2.gluonhq.com/jpackager/11/jdk.packager-linux.zip'
        - os: macos-latest
          display-name: 'osx'
          installerName: 'btviewer.dmg'
          jpackagerDownloadUrl: 'http://download2.gluonhq.com/jpackager/11/jdk.packager-osx.zip'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk+fx
      - name: Download jpackager
        run: curl -o jpackager.zip ${{ matrix.jpackagerDownloadUrl }}
      - name: Unzip jpackager
        run: unzip jpackager.zip -d $JAVA_HOME/bin
        shell: bash
      - name: Install with maven
        run: mvn install -B -e -q
      - name: Show current dir
        run: ls target/release
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.installerName }}
          path: target/release/*
  release:
    if: contains(github.ref, 'tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
  upload:
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension: [msi, deb, dmg]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: btviewer.${{ matrix.extension }}
          path: ./
      - name: Display downloaded files
        run: ls -R
      - name: Upload btviewer.${{ matrix.extension }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: .
          asset_name: btviewer.${{ matrix.extension }}
          asset_content_type: application/octet-stream