name: codacy-coverage-reporter

on:
  push:
    branches:
      - master
jobs:
  report-test-coverage:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk+fx
      - name: Build with maven
        env:
          JAVA_TOOLS_OPTIONS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.verbose=true"
        run: mvn -B package jacoco:report --file pom.xml
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./target/site/jacoco/jacoco.xml